# Generated by Django 3.0.5 on 2020-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reigsterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accesstrade',
            name='category',
            field=models.CharField(choices=[('Thời trang nữ', 'Thời trang nữ'), ('Thời trang nam', 'Thời trang nam'), ('Công nghẹ', 'Công nghẹ'), ('Đời sống', 'Đời sống'), ('Ô-tô/Xe máy', 'Ô-tô/Xe máy')], default='Thời trang nữ', max_length=200),
        ),
        migrations.AlterField(
            model_name='accesstrade',
            name='price',
            field=models.IntegerField(),
        ),
    ]
